### ISSUE TITLE
activity嵌套fragment

### ISSUE THREAD

**Issue by Chenayi** [yingLanNull/HideKeyboard#4]
搜索框是在activity的标题栏上的，怎样才能监听触摸fragment的内容时隐藏键盘

**Comment by yingLanNull** [comment]
请问你现在是在Activity中初始化然后在Fragment中触摸键盘不隐藏是吗，如果是建议你在Fragment中也初始化一下试试。

**Comment by Chenayi** [comment]
可以了，谢谢
